[package]
name = "actix-web-lab"
version = "0.9.0"
authors = ["Rob Ede <robjtede@icloud.com>"]
description = "In-progress extractors and middleware for Actix Web"
keywords = ["actix", "http", "web", "framework", "async"]
categories = [
    "network-programming",
    "asynchronous",
    "web-programming::http-server",
    "web-programming::websocket"
]
repository = "https://github.com/robjtede/actix-web-lab.git"
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.57"

[dependencies]
actix-web = { version = "4.0.0-beta.21", default-features = false }
actix-http = "3.0.0-beta.19"
actix-service = "2"
actix-utils = "3"
actix-files = "0.6.0-beta.15"

csv = "1.1"
bytes = "1"
derive_more = "0.99.5"
digest = "0.10"
futures-core = "0.3.7"
futures-util = { version = "0.3.7", default-features = false, features = ["std"] }
log = "0.4"
mime = "0.3"
once_cell = "1.8"
pin-project-lite = "0.2.7"
serde = "1"
serde_json = "1"
serde_urlencoded = "0.7"
tokio = { version = "1.13.1", features = ["sync"] }

[dev-dependencies]
env_logger = "0.9"
futures-util = { version = "0.3.7", default-features = false, features = ["std"] }
hex-literal = "0.3"
rand = "0.8"
sha2 = "0.10"
static_assertions = "1.1"
