version: 2.1

jobs:
  noop:
    docker: [{ image: alpine }]
    steps: [checkout]

workflows:
  version: 2
  skip_all:
    jobs:
      - noop: { filters: { branches: { ignore: 'rustdoc-gh-pages' } } }
